# -*- coding: utf-8 -*-
"""exerc. de python - karla

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lqvnjRHApUPRoxqqQIiAuP2E-rbx-iV3
"""

a=int(input("primeira variavel: "))
b=int(input("segunda variavel: "))
result=a+b
print("soma da variavel: ", result)

a=int(input("primeira variavel: "))
b=int(input("segunda variavel: "))
c=int(input("terceira variavel: "))
d=int(input("quarta variavel: "))
result=a+b+c+d
print("soma da variavel: ", result)

num1=int(input("primeira variavel: "))
num2=int(input("segunda variavel: "))
result=num1+num2
print("variaveis: ",result)